package models;

//Generated by Liubisheng
import java.util.ArrayList;
import java.util.List;

import play.db.jpa.Model;

public class BaseModel extends Model {
	
	 public static String ACTIVE = "Active";
	 public static String PROCESSING = "Processing";	 
	 public static String PENDING = "Pending";
	 public static String FREEZE = "Freeze";
	 public static String DELETE = "Delete";
	 public static String FINISH = "finish";
	 public static String REVIEW = "review";
	 public static String RETIRE = "Retire";
	 public static List<String> getBaseStates(){
		 List<String> ss = new ArrayList<String>();
		 ss.add(ACTIVE);
		 ss.add(PROCESSING);
		 ss.add(PENDING);
		 ss.add(FREEZE);
		 return ss;
	 }
 
}


